bundle:
	mkdir -p out
	cp -rf src/Cubes out/Cubes.app
	cp -rf ../sfmlcube/res out/Cubes.app/Contents/Resources/
	cp -rf ../sfmlcube/OSX-Release/sfmlcube out/Cubes.app/Contents/MacOS/
	cp -rf ../icon/Cubes.icns out/Cubes.app/Contents/Resources/
clean:
	rm -rf out